### ISSUE TITLE
End goals of FCP editor

### ISSUE THREAD

**Issue by Tomas-M** [pnp-software/fcp-editor#15]
I would like to better understand the final goals of the FCP Editor.
I will put here what comes to my mind now at the moment.

Lets assume the State Machines functionality is removed, and we are left only with Procedures. So, the FCP Editor will allow the user to make a diagram for a Procedure. The user will draw the diagram, and he will add some texts with the help of some autocomplete feature. What will happen next? Code generation is to be removed? So what is this editor for? Just to draw the Procedures on screen and that's all?

Furthermore, are we going to keep the current properties of a node? 

For example, FW Profile Editor has the following Action Node properties:
- action Node identifier
- adaptation point
- call function / define function / run code select box
- code text box input
- description text box input
- notes
- color

Do we need them all in FCP editor? 

Next, when we autocomplete, does the user need to put different text to different boxes? Should we autocomplete in one text box TAKING INTO CONSIDERATION some other text which the user entered in another text box? For example, if the user entered something to Description, and then he goes to write some text into CODE box, should the behavior of autocomplete functionality be different, for example by suggesting only certain autocompletions, but not some others, based on whats in the Description?

It's hard for me to explain, I hope you understand what I mean :)

I imagine we will need some more advanced autocompletion in place, which suggests only partially. Current autocompletion suggests basically everything. We will probably need for the autocompletion to understand the relations between things (eg. parameters etc). 

I am thinking about something similar such as some development tools have, or even microsoft excel if you use a function. I may provide some examples later if needed.

**Comment by pasetti** [comment]
This ticket can be closed: the first working release of the FCP Editor is now available. Some of the issues discussed here may crop up again in the future after we have some use-experience but, if they do, we will add dedicated tickets.
