### ISSUE TITLE
Autocompletion mechanism

### ISSUE THREAD

**Issue by Tomas-M** [pnp-software/fcp-editor#16]
Currently we have autocompletion mechanism which autocompletes strings when user starts to type #TM or #TC.
After autocompletion, the text in textbox remains such as #TM(1,1)_12345.
This seems very inconvnient to me since the user has probably no idea what it means.
What about making it differently?

When I initially implemented that, my main goal was to implement pure text-based autocomplete. But now since we need different logic, I should probably drop the idea of text-based autocompletion and we should switch to something more intelligent.

We could, for example, consider all texts to be a part of autocompletion. Thus it would not be needed to type #TM but user could start typing the DESCR itself, for example SES DAT_CMD_ and it would offer autocomplete for the given telecommands starting with that string. Space after SES should not be any problem.

User could trigger the autocomplete dialog by typing any text which can be autocompleted (eg. a parameter name), or by typing #. When the autocomplete is triggered, it should provide an extended dialog, where user can distinguish if he wants to type in telecommand, telemetry report, hk parameter, FCP reference, and so on.  Like here:

![image](https://user-images.githubusercontent.com/2259370/118616854-5d319100-b7c2-11eb-8a22-98edc62b7cc9.png)

**Comment by pasetti** [comment]
The auto-completion mechanism now works! I close the ticket.
