### ISSUE TITLE
Feedback From MIB Tables Upload

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fcp-editor#20]
I am experimenting with the upload of zipped files holding the MIB tables (through: `FcpEditorUrl/users.php`). In one of my experiments, I had made the following mistake: the zipped file should have contained file `pcf.dat` but, due to a typo, it contained file `pcfl.dat`. The upload process was successful and editor operation was successful too -- except that I did not have auto-completion for items which are in the PCF table! 

One way to avoid this kind of errors in the future would be if, at the end of the upload process, the editor sent back a message giving the list of tables which have been uploaded. In fact, it would be even better if the editor sent back a "table upload completed message" at the end of the processing of each table. This is because the upload process can be rather long (several minutes) and, while the upload is under way, it would be useful to have some indication that things are progressing. Or else some users will become impatient and assume that something has gone wrong and interrupt the upload.

NB: This is a minor issue which should be handled only if there is a simple solution for it. We can also live with the current implementation.

**Comment by Tomas-M** [comment]
Implementing progress indicator on both sides (browser-side and server-side) is indeed possible, but it is not trivial. So if you can live without the progress, I can put there simple wait indicator (rotating arrows). I can also put there some status indicating which tables were actually imported.

I made the changes by 4b2e1aaf40069174ff4f77101c310ce72f039ef7
I do not have example ZIP file here to test, so I couldn't test it properly here, please test on your end and let me know if there are any problems :-) Thank you

**Comment by Tomas-M** [comment]
When importing tables, it should print either "not found" status, or it should print full path in the ZIP file which was imported, as well as how many entries were found in the table.

**Comment by pasetti** [comment]
> Implementing progress indicator on both sides (browser-side and server-side) is indeed possible, but it is not trivial. So if you can live without the progress, I can put there simple wait indicator (rotating arrows). I can also put there some status indicating which tables were actually imported.

This is perfectly fine. Import is an infrequent operation, which is not done by the general user; hence a rotating arrow is enough (and I will also add a warning in the online help).

> When importing tables, it should print either "not found" status, or it should print full path in the ZIP file which was imported, as well as how many entries were found in the table.

This would be a good solution and would be give a clear indication of what went wrong.
