### ISSUE TITLE
Extension of Auto-Completion Mechanism

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fcp-editor#22]
I have a use case where we want to have more flexibility in the display of information in the auto-completion menu. The basic problem is that the information in the MIB tables is not sufficiently user-friendly. Hence, users would like to add two additional columns at the end of some MIB tables to hold the following fields:

- NNAME: the "nice" name of an item (an alphanumeric string with up to 64 characters)
- NDESCR: the "nice" description of an item (a text field with no length limitation)

In order to achieve this objective, we need two changes.

###  Change 1: Upload of New Fields
The upload menu currently looks like this:
![Screenshot from 2022-01-13 14-10-55](https://user-images.githubusercontent.com/15838404/149373691-d364522a-3aeb-4d10-9ff5-6924e7830e03.png)

We would need to add the NNAME and NDESCR fields to the following tables: PID, PCF, CCF, and CPC. This means that the "import instructions" in the upload table would look like this (new entries are bolded)

ccf: CCF_CNAME=1, CCF_DESCR=2, CCF_DESCR2=3, CCF_TYPE=7, CCF_STYPE=8, **CCF_NNAME=21, CCF_NDESCR=22**
cdf: CDF_CNAME=1, CDF_GRPSIZE=6, CDF_PNAME=7
cpc: CPC_PNAME=1, CPC_DESCR=2, CPC_PAFREF=11, **CPC_NNAME=16, CPC_NDESCR=17**
pas: PAS_NUMBR=1, PAS_ALTXT=2, PAS_ALVAL=3
pcf: PCF_NAME=1, PCF_DESCR=2, PCF_PID=3, **PCF_NNAME=24, PCF_NDESCCR=25**
pid: PID_TYPE=1, PID_STYPE=2, PID_SPID=6, PID_DESCR=7, **PID_NNAME=16, PID_NDESCR=17**
plf: PLF_NAME=1, PLF_SPID=2

In all cases, one can assume that NNAME is unique within each table.

### Change 2: Modify Auto-Completion Tables 
The second change concerns the generation of the auto-completion lists. Such lists are generated for 5 kinds of items: #TM, #HK, #EID, #TC, #TCPAR, The auto-completion list pops up when the user is writing in a text field and it has the form of a table. When the user selects a line in the table, an entry is made in the text field with a hovering tip. We would like to change the content of these auto-completion tables and of the hovering tips as described below.

**Telemetry Reports (#TM)**:
-  The auto-completion tables should have three columns: #TM(TYPE, STYPE) | NNAME | NDESCR
-  The text which appears when the user selects a line in the table should be: #TM(TYPE, STYPE):NNAME
-  The hovering tip should be: NDESCR

**Telemetry Parameters (#TMPAR)**:
- The auto-completion tables should have three columns: #TMPAR:NNAME | NDESCR | in TM(TYPE,STYPE):NNAME
- The text which appears when the user selects a line in the table should be: #TMPAR:NNAME
- The hovering tip should be: "NDESCR in TM(TYPE,STYPE):NNAME"
- Here, the string "TM(TYPE.STYPE):NNAME" refers to the telemetry packet holding the telemetry parameter

**Event Identifiers (#EID)**:
- The auto-completion tables should have three columns: #EID(TYPE,STYPE) | NNAME | NDESCR
- The text which appears when the user selects a line in the table should be: #EID(TYPE,STYPE):NNAME
- The hovering tip should be: NDESCR

**Telecommand Packets (#TC)**:
- The auto-completion tables should have three columns: #TC(TYPE,STYPE) | NNAME | NDESCR
- The text which appears when the user selects a line in the table should be: #TC(TYPE,STYPE):NNAME
- The hovering tip should be: NDESCR

**Telecommand Parameters (#TCPAR)**:
- The auto-completion tables should have three columns: #TCPAR:NNAME | NDESCR | in TC(TYPE,STYPE):NNAME
- The text which appears when the user selects a line in the table should be: #TCPAR:NNAME
- The hovering tip should be: "NDESCR in TM(TYPE,STYPE):NNAME"
- Here, the string "TC(TYPE.STYPE):NNAME" refers to the telecommand packet holding the telecommand parameter

One last point to be noted: while using the FCP Editor, I noticed that the autocompletion table will sometimes become too large to fit within the screen. The problem is the NDESCR field which can very large. I would therefore propose a third change to limit the maximum length of the NDESCR field when it appears in the auto-completion tables to, for instance, 64 characters (with ",,," added at the end if the actual length is longer)

**Comment by pasetti** [comment]
There may actually be a simpler way to handle this problem: I could re-label the columns in the MIB tables to fit the new purpose. for instance, a Telemetry Report (#TM) is currently handled as follows:

-     The auto-completion tables has three columns: #TM(TYPE, STYPE) | DESCR | SPID
-     The text which appears when the user selects a line in the table is: #TM(TYPE, STYPE):SPID
-     The hovering tip should be: DESCR

I could obtain the desired effect by re-labeling the columns in the PID table as follows:

- SPID --> NNAME
- DESCR --> NDESCR

This would still require some changes in the back-end because, in `users.php`, SPID is assumed to be an `int(11)` and should now be changed to be a `varchar(64)`. However, the changes would be less disruptive than in the original proposal. 

I need to consider this option more carefully.

**Comment by Tomas-M** [comment]
If the NNAME is unique, we can probably do it using the second method, simply modify the int(11) in database to varchar and rename the column names everywhere should be sufficient. In order to look more into it, I would kindly ask you for a sample ZIP file with SCOS database since I don't have any here, and I cannot find it anywhere. Thank you

**Comment by pasetti** [comment]
### Definition of New Approach for Handling Information in MIB Tables
The data which are read from the MIB tables are:

```
ccf: CCF_CNAME=1, CCF_DESCR=2, CCF_DESCR2=3, CCF_TYPE=7, CCF_STYPE=8, CCF_NNAME=21, CCF_NDESCR=22
cdf: CDF_CNAME=1, CDF_GRPSIZE=6, CDF_PNAME=7
cpc: CPC_PNAME=1, CPC_DESCR=2, CPC_PAFREF=11, CPC_NNAME=16, CPC_NDESCR=17
pas: PAS_NUMBR=1, PAS_ALTXT=2, PAS_ALVAL=3
pcf: PCF_NAME=1, PCF_DESCR=2, PCF_PID=3, PCF_NNAME=24, PCF_NDESCCR=25
pid: PID_TYPE=1, PID_STYPE=2, PID_SPID=6, PID_DESCR=7, PID_NNAME=16, PID_NDESCR=17
plf: PLF_NAME=1, PLF_SPID=2
```

The bolded items are new. The NNAME field represents a "nice name" and is a varchar(64). The NDESCR field represents a "nice description" and is a text field with unlimited length. A general description of the MIB tables can be found in ticket #8. One problem is that the NNAME and NDESCR fields are optional: not all users will have them. 

The items which we want to handle through the auto-completion lists are:

-    #TM: TM Packets,
-    #EID: Events, namely packets with STYPE equal to 5,
-    #TMPAR: Parameters in a TM Packet
-    #HK: Housekeeping parameter, namely TM parameters with PCF_PID different from NULL
-    #TC: Telecommands
-    #TCPAR: Parameters in a telecommand

These items are entered by the user in the text fields of the editor. The user selects them from auto-completion lists. The auto-completion lists take the form of tables with three columns. The users selects an entry from the list and the entry is displayed as a hyperlink with a tooltip. Hence, for each item, we must define:

-    The content of the three columns in the autocompletion table
-    The text which is displayed when an autocompletion entry is selected by the user
-    The text in the tooltip

Below, I discuss this definition for each items to be disaplayed. I use names in CamelCase for the logical information which is associated to each item. This logical information should be configurable by the user.

**TM Packets (#TM)**

-    The auto-completion tables should have three columns: #TM(TYPE, STYPE) | TmPacketName | TmPacketDesc
-    The text which appears when the user selects a line in the table should be: #TM(TYPE, STYPE):TmPacketName
-    The hovering tip should be: TmPacketDesc

TmPacketName may be mapped either to PID_NNAME, or to PID_SPID, or to PID_DESCR.
TmPacketDesc may be mapped either to PID_DESCR or to PID_NDESCR

**Event Identifiers (#EID)**

-    The auto-completion tables should have three columns: #EID(TYPE,STYPE) | TmPacketName | TmPacketDesc
-    The text which appears when the user selects a line in the table should be: #EID(TYPE,STYPE):TmPacketName
-    The hovering tip should be: TmPacketDesc

TmPacketName may be mapped either to PID_NNAME, or to PID_SPID, or to PID_DESCR.
TmPacketDesc may be mapped either to PID_DESCR or to PID_NDESCR

**Telemetry Parameters (#TMPAR)**

-    The auto-completion tables should have three columns: #TMPAR:TmParName | TmParDescr | in TM(TYPE,STYPE):TmPacketName
-    The text which appears when the user selects a line in the table should be: #TMPAR:TmParName
-    The hovering tip should be: "TmParDescr in TM(TYPE,STYPE):NNAME"

The string "TM(TYPE.STYPE):TmPacketName" refers to the telemetry packet holding the telemetry parameter.
TmParName may be mapped either to PCF_NAME, or to PCF_DESCR or to PCF_NNAME.
TmParDescr may be mapped either to PCF_DESCR, or to PCF_NDESCR

**Housekeeping Parameters (#HK)**

-    The auto-completion tables should have three columns: #HK:TmParName | TmParDescr | in TM(TYPE,STYPE):TmPacketName
-    The text which appears when the user selects a line in the table should be: #HK:TmParName
-    The hovering tip should be: "TmParDescr in TM(TYPE,STYPE):NNAME"

The string "TM(TYPE.STYPE):TmPacketName" refers to the telemetry packet holding the telemetry parameter.
TmParName may be mapped either to PCF_NAME, or to PCF_DESCR or to PCF_NNAME.
TmParDescr may be mapped either to PCF_DESCR, or to PCF_NDESCR

**Telecommand  (#TC)**

-    The auto-completion tables should have three columns: #TC(TYPE,STYPE) | TcName | TcDesc
-    The text which appears when the user selects a line in the table should be: #TC(TYPE,STYPE):TcName
-    The hovering tip should be: TcDesc

TcName may be mapped either to CCF_CNAME, or to CCF_DESCR, or to CCF_NNAME
TcDesc may be mapped either to CCF_DESCR, CCF_DESCR2, or to CCF_NDESCR

**Telecommand Parameter (#TCPAR)**

-    The auto-completion tables should have three columns: #TCPAR:TcParName | TcParDescr | in TC(TYPE, STYPE):TcName
-    The text which appears when the user selects a line in the table should be: #TCPAR:TcParName
-    The hovering tip should be: TcParDescr

The string "TC(TYPE.STYPE):TcName" refers to the telecommand holding the telecommand parameter.
TcParName may be mapped either to CPC_CNAME, or to CPC_DESCR, or to CPC_NNAME
TcDesc may be mapped either to CPC_DESCR, CPC_NDESCR

### Configurability
Somewhere the user has to define how the logical names (TmPacketName, TmPacketDescr, TcName, etc) are mapped to the fields in the MIB tables. This configuration is done once by each user and should never change afterwards (but different users may make different choices). Hence, I would say that a simple solution would be to have a json file which the user has to fill in before he starts using the editor. But there may be other (better) solutions ...

**Comment by pasetti** [comment]
Hello Tomas, I sent you the ZIP by e-mail (the last one was on 16 Jan at 10:45 pm -- did you receive it?)

**Comment by Tomas-M** [comment]
Oh, I can see your emails ended in spam, I didn't even know you wrote to me directly. Stupid gmail. 
I am sorry I didnt find it earlier.
Now I have the ZIP file and I will go through the github issue again.
Thank you

**Comment by pasetti** [comment]
I realize that this change is difficult to explain. In order to illustrate what I think is needed, I have made a very basic implementation of the new mechanism in the ext_auto_comp branch. I have made two changes.

(1) In `users.php`, I added the NNAME and NDESCR columns to the CCF, CPC, PCF and PID tables. 
(2) In `autocomplete.js`, I have introduced variables `tmPacketName`, `tmPacketDescr`, `tmPacketDescrShort`, etc. These new variables represent the values which should be displayed to the user. In the example in the new branch, I have mapped `tmPacketName` to `NNAME`, `tmPacketDescr` to `NDESCR`, etc. In the example, the mapping is hard-coded. Ideally, this mapping should be configurable for the user (perhaps by being stored in a json file on the server -- as I said above, the mapping will not change or will change very infrequently).

I have tested the example on `localhost` and it seems to work. I am not sure whether it is a good solution (probably not because configuration information is hard-coded) but it should at least illustrate the problem.

**Comment by Tomas-M** [comment]
I understand what you want to achieve, I am just thinking about the best approach.
Maybe your approach is the best :) I will review your branch.

**Comment by Tomas-M** [comment]
I've firstly modified your changes a little bit to limit the width of table column differently (using css), in 6b13fca9a691d87bd831cc526d58c8e7660e04ad
Then I made the column names parametric, in 70f2a8cf36b5a4a91d162feca5ae65a8b2066516
Please test if this suits your needs. 

We could let the users edit this in the editor, for example in an input field under the feature called
"Edit values which are assigned to transition identifiers"
(in menu, Actions, at the very bottom)

Let me know please if this looks OK for you. Thank you.

**Comment by Tomas-M** [comment]
And a small bugfix applied by 785c9a7e3cffcf5f26ced87241da05a3b1fc12e7, please make sure to checkout whole branch

**Comment by pasetti** [comment]
I tested the latest changed and bug fixes and all seems to work as expected:

>We could let the users edit this in the editor, for example in an input field under the feature called
>"Edit values which are assigned to transition identifiers"
>(in menu, Actions, at the very bottom)

For the time being, I have just explained that the mapping from SCOS to Logical Names is done in `autocomplete.js`. I am going to test this implementation on a more realistic use-case and then we could also implement this change.

**Comment by Tomas-M** [comment]
I've pushed one more little change to ensure the editor does not fail if the given columns do not exist in database (eg. user misspelled them or such). It will return "undefined" instead of failing. Commit dacf4c00dab4dd14683b4765040b3ddde808056e

**Comment by pasetti** [comment]
Thanks, Tomas. This is indeed a useful change. I incorporated in release 1.3.0 of the editor.

**Comment by pasetti** [comment]
I have just realized something interesting. The current implementation of `autocomplete,js` assumes that the names and descriptions of the database items which are displayed in the editor are read from the NNAME and NDESCR fields of the database.

Suppose that we wanted to change to a situation where, for telecommands, we want to show the CNAME instead of the NNAME. I had originally assumed that this would require us to update the mapping from the database field names to the display names in `autocomplete.js`. But, in fact, there is a simpler solution: when we load the MIB tables, we would only have to change NNAME to point to the same field as CNAM:

`ccf: CCF_CNAME=1, CCF_DESCR=2, CCF_DESCR2=3, CCF_TYPE=7, CCF_STYPE=8, CCF_NNAME=1, CCF_NDESCR=22 `

With setting, the NNAME field of the autocompletion tables will have the same content as the CNAME field, which is precisely what we want. On this bases, I close the ticket since we now have all we need.

**Comment by Tomas-M** [comment]
Looks like this little change didn't make it to the master (main) repo
dacf4c00dab4dd14683b4765040b3ddde808056e
I merged it now

**Comment by pasetti** [comment]
OK. Thanks for the merge.
