### ISSUE TITLE
Input Variables of Type String

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fcp-editor#26]
On the "Global Properties" table, I can enter the "input variables". For each input variable, I must select the type and provide a default value. If I select "string", I cannot enter a string-iike input because the editor only accepts numbers.

**Comment by Tomas-M** [comment]
Implemented by 498e540fd95ac630810a9123b09e876a4dfdd0cc
I've merged the test branch to main.

Side note.
On my browser (chrome), I can see an annoying problem, chrome thinks that the "value" input box in global properties is an input field for username, and it puts there my username (eg example@slax.org) as a default value. I wasn't able to get rid of that, unfortunately there seems to be no way to force the browser to stop doing this. It is really annoying but I don't really know what to do with that.

**Comment by pasetti** [comment]
I checked the change on firefox and it works fine. On Chrome, I have noticed the same issue reported by Tomas (the "value" input box is filled with the user name). This is a bit annoying but, given that there is no easy way to get rid of it, it is acceptable

**Comment by Tomas-M** [comment]
It drives me crazy.
I've pushed an ugly workaround, which simply sets the value of the fields to the same value which should be in the fields, one second after the page is loaded in browser. It seems like it overrides the autocompletion. I have no other solution for this, and the internet is full of people fighting the same issue with zero success for years. Feel free to test c51c7e15966977be56617da5c1067ef2d589737f

**Comment by Tomas-M** [comment]
I can optionally merge this to FW Profile editor (-pub) as well, it looks like it could help there too. Let me know please if this is what you want. Thanks
