### ISSUE TITLE
Indententation in Text Fields

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fcp-editor#27]
In the FW Profile, editor a change was recently implemented (after the FCP Editor was forked from it) to keep the indentation in the notes (commit d2fa13652ed75ec4c34e67e6ffd8bcf46cbfb81f). Only the lib.js file was affected with the following change:
![image](https://user-images.githubusercontent.com/15838404/153172486-61e7ec9d-41b5-46b3-b59b-6e12a5ce91e1.png)

This is a very useful change and I would propose to also have it in the FCP Editor (in fact, I would propose to have it both for notes and for action nodes -- if it can be done without too much difficulty).

**Comment by Tomas-M** [comment]
> This is a very useful change and I would propose to also have it in the FCP Editor

The change you mentioned is already in FCP editor.
However the way how I replace the text for adding tooltips broke that.
Took me a while to find out what the problem was. It has been addressed by cc3ff6363e76eac0bcfe73356be780f5b2c061d9
Please test

**Comment by pasetti** [comment]
I checked the change and it appears to work as expected
