### ISSUE TITLE
Model Name Check When Saving a Model 

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fcp-editor#29]
One useful "safety" feature (hopefully not too hard too implement) would be as follows: suppose you have edited a model called "ABC" and you want to save it. Normally, you just overwrite the existing copy of model "ABC" but sometimes, either by mistake or intentionally, you may want to overwrite a different model. In order to avoid mistakes, it would be useful to have a check such that if a user tries to save model "ABC" to a model with a different name "XYZ", then a pop-up appears asking the user to confirm that he really wants to overwrite model "XYZ".

**Comment by Tomas-M** [comment]
There is already a popup window with confirmation.
If user tries to overwrite existing file (diagram), it asks if he wants to overwrite it.
I can perhaps change the color of the popup window to red, in cases when user tries to save under a different name.
I will implement it and you can see if this is something you want.

**Comment by Tomas-M** [comment]
Implemented here, please test
e36a11162c0f9c7c6553d7c4c8da9dd299f63d5a

I decided to go this way:
- if the name is the same when saving, the save button is green
- if the name is different, save button is red, and warning is displayed at the bottom

**Comment by Tomas-M** [comment]
Let me know please if this is sufficient for you.
Thank you

**Comment by pasetti** [comment]
Thanks Tomas. I tested the new feature and it looks fine. I therefore proceed to close the ticket.
